[[main]]
  name = "Diensten"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Projecten"
  pageRef = "/services/"
  weight = 20

  [[main]]
    parent = "Projecten"
    name = "Renovatie"
    pageRef = "/services/#renovations"
    weight = 21

  [[main]]
    parent = "Projecten"
    name = "Extensions"
    pageRef = "/services/#extensions"
    weight = 22

  [[main]]
    parent = "Projecten"
    name = "Bathroom Renovation"
    pageRef = "/services/#bathroom"
    weight = 23

  [[main]]
    parent = "Projecten"
    name = "Kitchen Renovation"
    pageRef = "/services/#kitchen"
    weight = 24

  [[main]]
    parent = "Projecten"
    name = "Electricity"
    pageRef = "/services/#electricity"
    weight = 25

  [[main]]
    parent = "Projecten"
    name = "Flooring and underfloor heating"
    pageRef = "/services/#flooring"
    weight = 26

  [[main]]
    parent = "Projecten"
    name = "Windows"
    pageRef = "/services/#windows"
    weight = 26

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 50

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation
